version: '3.1'

services:
  database:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: monitoring_dev_user
      POSTGRES_PASSWORD: monitoring_dev_password
    ports:
      - 5433:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql